apiVersion: admin.enmasse.io/v1beta2
kind: AddressSpacePlan
metadata:
  labels:
    app: enmasse
  name: scenario2-dev
  namespace: enmasse-infra
spec:
  addressPlans:
  - scenario2-queue
  - scenario2-topic
  addressSpaceType: brokered
  displayName: Scenario2-DEV
  displayOrder: 0
  infraConfigRef: scenario2infraconfig-non-prod
  resourceLimits:
    broker: 2
    
